/**
 * A `reviewer: by-pass - <reason>` marker takes the block after it out of review. What counts as "the
 * block" -- braces, an indentation body, one statement, an else/catch chain -- is pinned here, case by
 * case, because a region that ends a line too early lets a finding through and one that runs a line
 * too far hides one.
 */

import { describe, expect, it } from "bun:test";

import { type BypassRegionRecord } from "../../src/core/ports/review-reporter";
import {
  type BypassRegion,
  bypassWarning,
  countBypassed,
  describeRegion,
  isMarkdownPath,
  isWhollyBypassed,
  scanBypass,
} from "../../src/core/review/bypass";

import { casesUnder, loadFixture } from "./fixtures";

const bypass = loadFixture("bypass");

describe("scanning a file for bypass markers", () => {
  it.each(casesUnder<string[], { regions: BypassRegion[]; unreasoned: number[] }>(bypass, "scan"))(
    "$name",
    ({ input, expected }) => {
      expect(scanBypass(input)).toEqual({ ...expected, added: [] });
    },
  );

  it("does not honour a marker on a line the change added: a change cannot bypass its own review", () => {
    const lines = [
      "// reviewer: by-pass - generated",
      "export function decode() {",
      "  return 1;",
      "}",
      "// reviewer: by-pass - trust me",
      "export function login() {",
      "  return true;",
      "}",
    ];
    const scan = scanBypass(lines, { addedLines: new Set([5, 6, 7]) });
    expect(scan.regions).toEqual([{ start: 1, end: 4, reason: "generated" }]);
    expect(scan.added).toEqual([{ line: 5, reason: "trust me" }]);
  });

  it("honours a marker the base already had, whatever the change added inside its block", () => {
    const lines = [
      "// reviewer: by-pass - generated",
      "export function decode() {",
      "  hack();",
      "}",
    ];
    const scan = scanBypass(lines, { addedLines: new Set([3]) });
    expect(scan.regions).toEqual([{ start: 1, end: 4, reason: "generated" }]);
    expect(scan.added).toEqual([]);
  });

  it("reads no marker inside a Markdown code fence: an example is not an instruction", () => {
    const lines = [
      "# Bypassing",
      "```ts",
      "// reviewer: by-pass - generated by protoc",
      "export function decode() {}",
      "```",
      "<!-- reviewer: by-pass - generated table -->",
      "| a | b |",
    ];
    expect(scanBypass(lines, { isMarkdown: true }).regions).toEqual([
      { start: 6, end: 7, reason: "generated table" },
    ]);
    // The same lines in a source file are read as written.
    expect(scanBypass(lines).regions.map((region) => region.start)).toContain(3);
  });

  it.each([
    ["README.md", true],
    ["docs/guide.MDX", true],
    ["notes.markdown", true],
    ["src/a.ts", false],
    ["md", false],
  ])("reads %s as Markdown: %s", (path, expected) => {
    expect(isMarkdownPath(path)).toBe(expected);
  });

  it("reads a file of any size in one pass", () => {
    // A marker whose block never closes scans to the end; a hundred of them must not go quadratic.
    const lines = Array.from({ length: 50_000 }, (_, index) =>
      index % 500 === 0 ? "// reviewer: by-pass - perf" : "  a();",
    );
    const started = performance.now();
    const { regions } = scanBypass(lines);
    expect(performance.now() - started).toBeLessThan(2000);
    expect(regions).toHaveLength(100);
  });
});

describe("how many added lines the regions take", () => {
  it.each(
    casesUnder<{ lines: number[]; regions: BypassRegion[] }, number>(bypass, "count_bypassed"),
  )("$name", ({ input, expected }) => {
    expect(countBypassed(new Set(input.lines), input.regions)).toBe(expected);
  });
});

describe("whether a file has anything left to review", () => {
  it.each(
    casesUnder<{ lines: number[]; regions: BypassRegion[] }, boolean>(bypass, "wholly_bypassed"),
  )("$name", ({ input, expected }) => {
    expect(isWhollyBypassed(new Set(input.lines), input.regions)).toBe(expected);
  });
});

describe("how a region reads", () => {
  it.each(casesUnder<BypassRegionRecord, string>(bypass, "describe"))(
    "$name",
    ({ input, expected }) => {
      expect(describeRegion(input)).toBe(expected);
    },
  );

  it.each(casesUnder<BypassRegionRecord[], string>(bypass, "warning"))(
    "warning: $name",
    ({ input, expected }) => {
      expect(bypassWarning(input)).toBe(expected);
    },
  );
});
