/**
 * Bypass markers in the flow, against real git. The scan itself is pinned by
 * `tests/contracts/bypass.contract.test.ts` and the view with regions left out by
 * `tests/contracts/diff.contract.test.ts`; what these check is everything
 * around them: that the whole file is read so a block can run past the hunk,
 * that neither the model nor the verifier is shown a bypassed line, that a file
 * bypassed whole calls no model, that the setting switches it off, and that
 * every path out of the report leaves a count and a log line behind.
 */

import { describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { type Finding, finding } from "../../../src/core/domain/finding";
import {
  type BranchReviewRecord,
  type SummaryRecord,
} from "../../../src/core/ports/review-reporter";
import {
  type BranchReviewOptions,
  branchReviewText,
  iterBranchReview,
  reviewBranch,
} from "../../../src/core/review/branch-review";
import { type ReviewFileInput } from "../../../src/core/review/file-reviewer";
import {
  DEFAULT_FILE_REVIEW_SETTINGS,
  type PerFileReviewer,
} from "../../../src/core/review/review-file";
import { type Verdict, type VerifyInput } from "../../../src/core/review/verify";
import { LocalGitReader } from "../../../src/providers/git/local-git";
import { git } from "../../helpers/git";
import { recordingLogger } from "../../helpers/logging";

/** A long function: its body outruns the three context lines a hunk shows. */
const LEGACY_BODY = Array.from({ length: 12 }, (_, index) => `  step${index}();`).join("\n");

/** The base already marks `legacy` bypassed: a marker is honoured once it is merged. */
const SVC_BEFORE = `import { x } from "./x";

export function fresh() {
  return x;
}

// reviewer: by-pass - legacy, scheduled for removal
export function legacy() {
${LEGACY_BODY}
}
`;

/**
 * The feature adds a line at the top of `legacy`'s body, so the hunk ends three lines into a body that
 * runs on for twelve; then adds a line at the very end, outside any block.
 */
const SVC_AFTER = `import { x } from "./x";

export function fresh() {
  return x;
}

// reviewer: by-pass - legacy, scheduled for removal
export function legacy() {
  added();
${LEGACY_BODY}
}

export const tail = 1;
`;

/** Generated code the base already marks. */
const WHOLE_BEFORE = `// reviewer: by-pass - generated by protoc
export function decode(buffer) {
  return buffer;
}
`;

/** Every added line lies in the bypassed block. */
const WHOLE = `// reviewer: by-pass - generated by protoc
export function decode(buffer) {
  check(buffer);
  return buffer;
}
`;

/** A marker without a reason, above code. */
const BAD = `// reviewer: by-pass
export function risky() {
  return 1;
}
`;

const PLAIN = `export const plain = 2;\n`;

/**
 * `main` holds `svc.ts` and `whole.ts`, both marked; `feature` edits them as above and adds `bad.ts` and
 * `plain.ts`. The checkout is left on `feature`.
 */
function repo(): string {
  const root = mkdtempSync(join(tmpdir(), "reviewer-bypass-"));
  git(root, "init", "-b", "main", "-q");
  git(root, "config", "user.email", "t@example.com");
  git(root, "config", "user.name", "Test");
  writeFileSync(join(root, "svc.ts"), SVC_BEFORE);
  writeFileSync(join(root, "whole.ts"), WHOLE_BEFORE);
  git(root, "add", "-A");
  git(root, "commit", "-qm", "base");
  git(root, "checkout", "-q", "-b", "feature");
  writeFileSync(join(root, "svc.ts"), SVC_AFTER);
  writeFileSync(join(root, "whole.ts"), WHOLE);
  writeFileSync(join(root, "bad.ts"), BAD);
  writeFileSync(join(root, "plain.ts"), PLAIN);
  git(root, "add", "-A");
  git(root, "commit", "-qm", "feature work");
  return root;
}

/** Reports one finding on every allowed line, its body naming the line, so what was left out is legible. */
class EveryLineReviewer implements PerFileReviewer {
  readonly seen: string[] = [];
  /** Every prompt input, by path, so a test can read what the model was shown. */
  readonly inputs = new Map<string, ReviewFileInput>();

  reviewFile(input: ReviewFileInput): Promise<Finding[]> {
    this.seen.push(input.path);
    this.inputs.set(input.path, input);
    return Promise.resolve(
      [...input.allowedLines]
        .toSorted((a, b) => a - b)
        .map((line) => finding({ line, severity: "bug", body: `L${line}` })),
    );
  }
}

/** Keeps everything; records which findings it was asked about and the diff it was shown. */
class RecordingVerifier {
  readonly asked: string[] = [];
  readonly diffs = new Map<string, string>();

  verify(input: VerifyInput): Promise<Verdict> {
    this.asked.push(...input.findings.map((f) => `${input.path}:${f.body}`));
    this.diffs.set(input.path, input.annotatedPatch);
    return Promise.resolve({ kept: [...input.findings], refuted: [] });
  }
}

function options(
  root: string,
  overrides: Partial<Omit<BranchReviewOptions, "reviewer">> = {},
): BranchReviewOptions & { reviewer: EveryLineReviewer } {
  return {
    base: "main",
    git: new LocalGitReader(root),
    settings: DEFAULT_FILE_REVIEW_SETTINGS,
    skills: null,
    maxConcurrentFiles: 4,
    ...overrides,
    reviewer: new EveryLineReviewer(),
  };
}

/** The lines of `text`, numbered from one, that satisfy `test`. */
function linesWhere(text: string, isWanted: (line: string) => boolean): number[] {
  return text.split("\n").flatMap((line, index) => (isWanted(line) ? [index + 1] : []));
}

const MARKER_LINE = linesWhere(SVC_AFTER, (line) => line.includes("by-pass"))[0] ?? 0;
const LEGACY_END = linesWhere(SVC_AFTER, (line) => line === "}").at(-1) ?? 0;
const TAIL_LINE = linesWhere(SVC_AFTER, (line) => line.startsWith("export const tail"))[0] ?? 0;
const ADDED_LINE = linesWhere(SVC_AFTER, (line) => line === "  added();")[0] ?? 0;

describe("a block bypassed from inside the code", () => {
  it("reads the whole file, so the region runs past the hunk to the block's real end", async () => {
    const result = await reviewBranch(options(repo()));
    expect(result.bypass_regions).toContainEqual({
      path: "svc.ts",
      start_line: MARKER_LINE,
      end_line: LEGACY_END,
      reason: "legacy, scheduled for removal",
    });
    // Sanity: the hunk cannot have shown the block's end, or the test proves nothing.
    expect(LEGACY_END - ADDED_LINE).toBeGreaterThan(3);
  });

  it("shows the model the diff with the region replaced by one line, and only the lines outside it as allowed", async () => {
    const o = options(repo());
    await reviewBranch(o);
    const input = o.reviewer.inputs.get("svc.ts");
    expect(input?.annotatedPatch).toContain(
      `[bypassed lines ${MARKER_LINE}-${LEGACY_END}: legacy, scheduled for removal]`,
    );
    expect(input?.annotatedPatch).not.toContain("added();");
    expect(input?.annotatedPatch).not.toContain("by-pass");
    expect(input?.annotatedPatch).toContain(`[L${TAIL_LINE}] +export const tail = 1;`);
    // The blank line before `tail` is an added line too.
    expect([...(input?.allowedLines ?? [])].toSorted((a, b) => a - b)).toEqual([
      TAIL_LINE - 1,
      TAIL_LINE,
    ]);
    expect(input?.hasBypassedLines).toBe(true);
    // The anchor haystack is the shown diff's: a quote from the block cannot place a finding.
    expect(input?.anchorIndex?.some(([line]) => line === ADDED_LINE)).toBe(false);
  });

  it("leaves the region out of the file text too, the same line standing where it was", async () => {
    const o = options(repo());
    await reviewBranch(o);
    const content = o.reviewer.inputs.get("svc.ts")?.content ?? "";
    expect(content).toContain("export function fresh() {");
    expect(content).toContain(
      `[bypassed lines ${MARKER_LINE}-${LEGACY_END}: legacy, scheduled for removal]`,
    );
    expect(content).not.toContain("step0();");
    expect(content).toContain("export const tail = 1;");
  });

  it("tells a file with no marker nothing about bypassing", async () => {
    const o = options(repo());
    await reviewBranch(o);
    const input = o.reviewer.inputs.get("plain.ts");
    expect(input?.hasBypassedLines).toBe(false);
    expect(input?.annotatedPatch).not.toContain("[bypassed");
  });

  it("reports only the findings outside the region, and counts the added lines the region hid", async () => {
    const result = await reviewBranch(options(repo()));
    const onSvc = result.findings.filter((f) => f.path === "svc.ts").map((f) => f.line);
    expect(onSvc).toEqual([TAIL_LINE - 1, TAIL_LINE]);
    // svc.ts: the added body line; whole.ts: its one added line, bypassed whole.
    expect(result.bypassed).toBe(1 + 1);
  });

  it("shows the verifier the same diff the reviewer saw, so it too never reads a bypassed line", async () => {
    const verifier = new RecordingVerifier();
    const o = options(repo(), { verifier });
    await reviewBranch(o);
    expect(verifier.diffs.get("svc.ts")).toBe(o.reviewer.inputs.get("svc.ts")?.annotatedPatch);
    expect(verifier.asked.filter((entry) => entry.startsWith("svc.ts:"))).toEqual([
      `svc.ts:L${TAIL_LINE - 1}`,
      `svc.ts:L${TAIL_LINE}`,
    ]);
    expect(verifier.asked.some((entry) => entry.startsWith("whole.ts:"))).toBe(false);
  });

  it("calls no model for a file whose every added line is bypassed, and counts it as skipped", async () => {
    const o = options(repo());
    const result = await reviewBranch(o);
    expect(o.reviewer.seen).not.toContain("whole.ts");
    expect(result.skipped["bypassed"]).toBe(1);
    expect(result.files_reviewed).toBe(3);
    // The arithmetic still closes: 4 changed = 3 reviewed + 0 failed + 1 skipped.
    expect(result.files_changed).toBe(
      result.files_reviewed +
        result.failed +
        Object.values(result.skipped).reduce((a, b) => a + b, 0),
    );
    expect(result.bypass_regions).toContainEqual({
      path: "whole.ts",
      start_line: 1,
      end_line: 5,
      reason: "generated by protoc",
    });
  });

  it("does not honour a marker without a reason, and says so", async () => {
    const lines: string[] = [];
    const result = await reviewBranch(options(repo(), { logger: recordingLogger(lines) }));
    expect(result.findings.filter((f) => f.path === "bad.ts").map((f) => f.line)).toEqual([
      1, 2, 3, 4,
    ]);
    expect(result.bypass_regions.some((region) => region.path === "bad.ts")).toBe(false);
    expect(lines).toContain(
      "WARNING bad.ts:1: 'reviewer: by-pass' without a reason; not honoured.",
    );
  });

  it("lists regions by path then line, and leaves an untouched file alone", async () => {
    const result = await reviewBranch(options(repo()));
    expect(result.bypass_regions.map((region) => region.path)).toEqual(["svc.ts", "whole.ts"]);
    expect(result.findings.filter((f) => f.path === "plain.ts")).toHaveLength(1);
  });

  it("logs every region it honoured and how many added lines each file lost to them", async () => {
    const lines: string[] = [];
    await reviewBranch(options(repo(), { logger: recordingLogger(lines) }));
    expect(lines).toContain(
      `INFO svc.ts: lines ${MARKER_LINE}-${LEGACY_END} bypassed (legacy, scheduled for removal).`,
    );
    expect(lines).toContain(
      "INFO skip whole.ts: every added line lies in a bypassed region; the model was not called.",
    );
    const reviewLine = lines.find((line) => line.startsWith("INFO review svc.ts:")) ?? "";
    expect(reviewLine).toContain("+3 line(s), 1 bypassed, ");
    const plainLine = lines.find((line) => line.startsWith("INFO review plain.ts:")) ?? "";
    expect(plainLine).not.toContain("bypassed");
  });

  it("carries the counts and the regions on the summary record", async () => {
    const stream = iterBranchReview(options(repo()));
    const records: BranchReviewRecord[] = await Array.fromAsync(stream);
    const summary = records.at(-1) as SummaryRecord;
    expect(summary.type).toBe("summary");
    expect(summary.bypassed).toBe(2);
    expect(summary.bypass_added).toEqual([]);
    expect(summary.skipped).toEqual({ bypassed: 1 });
    expect(summary.bypass_regions).toHaveLength(2);
  });
});

describe("the bypass-markers setting", () => {
  it("off: every marker is ignored, the whole file is reviewed, and the log says the markers were there", async () => {
    const lines: string[] = [];
    const o = options(repo(), {
      settings: { ...DEFAULT_FILE_REVIEW_SETTINGS, bypassMarkers: false },
      logger: recordingLogger(lines),
    });
    const result = await reviewBranch(o);
    expect(result.bypassed).toBe(0);
    expect(result.bypass_regions).toEqual([]);
    expect(result.skipped).toEqual({});
    expect(o.reviewer.seen).toContain("whole.ts");
    // Off means shown in full: the block's lines are in the diff, and nothing says bypassed.
    const input = o.reviewer.inputs.get("svc.ts");
    expect(input?.annotatedPatch).toContain("added();");
    expect(input?.annotatedPatch).not.toContain("[bypassed");
    expect(input?.hasBypassedLines).toBe(false);
    expect(result.findings.filter((f) => f.path === "svc.ts").map((f) => f.line)).toEqual([
      ADDED_LINE,
      TAIL_LINE - 1,
      TAIL_LINE,
    ]);
    expect(lines).toContain(
      "INFO svc.ts: bypass markers present, but bypass-markers is off; reviewed in full.",
    );
    expect(lines).toContain(
      "INFO bad.ts: bypass markers present, but bypass-markers is off; reviewed in full.",
    );
  });
});

/** `feature` goes on to mark `fresh` bypassed and add a line to it, in one more commit. */
function markedByTheChange(): string {
  const root = repo();
  writeFileSync(
    join(root, "svc.ts"),
    SVC_AFTER.replace(
      "export function fresh() {\n  return x;",
      "// reviewer: by-pass - trust me\nexport function fresh() {\n  log();\n  return x;",
    ),
  );
  git(root, "commit", "-qam", "mark fresh");
  return root;
}

describe("a marker the change adds itself", () => {
  it("is not honoured: the block is shown and reviewed, and the marker is named", async () => {
    // A pull request could otherwise take its own code out of its own review.
    const lines: string[] = [];
    const o = options(markedByTheChange(), { logger: recordingLogger(lines) });
    const result = await reviewBranch(o);
    expect(o.reviewer.inputs.get("svc.ts")?.annotatedPatch).toContain("log();");
    expect(result.findings.filter((f) => f.path === "svc.ts").map((f) => f.line)).toContain(5);
    expect(result.bypass_regions.map((region) => region.reason)).not.toContain("trust me");
    expect(result.bypass_added).toEqual([{ path: "svc.ts", line: 3, reason: "trust me" }]);
    expect(lines).toContain(
      "WARNING svc.ts:3: 'reviewer: by-pass' added by this change; not honoured until it is merged (trust me).",
    );
  });

  it("is still the change's own on a --since run whose diff starts after it was added", async () => {
    // Push one adds the marker, push two adds code under it: to the incremental run the marker is a
    // context line, yet it is not merged. The change's whole diff against the base decides.
    const root = markedByTheChange();
    git(root, "tag", "marked");
    writeFileSync(
      join(root, "svc.ts"),
      readFileSync(join(root, "svc.ts"), "utf8").replace("  log();", "  log();\n  exfiltrate();"),
    );
    git(root, "commit", "-qam", "second push");
    const o = options(root, { since: "marked" });
    const result = await reviewBranch(o);
    expect(o.reviewer.inputs.get("svc.ts")?.annotatedPatch).toContain("exfiltrate();");
    expect(result.bypass_added).toEqual([{ path: "svc.ts", line: 3, reason: "trust me" }]);
  });

  it("in uncommitted work is the author's own too, and a committed one is honoured", async () => {
    const root = repo();
    writeFileSync(
      join(root, "svc.ts"),
      SVC_AFTER.replace(
        "export function fresh() {\n  return x;",
        "// reviewer: by-pass - wip\nexport function fresh() {\n  log();\n  return x;",
      ),
    );
    const result = await reviewBranch(options(root, { uncommitted: true }));
    expect(result.findings.filter((f) => f.path === "svc.ts").map((f) => f.line)).toEqual([3, 5]);
    expect(result.bypass_added).toEqual([{ path: "svc.ts", line: 3, reason: "wip" }]);
    expect(result.bypass_regions).toEqual([
      {
        path: "svc.ts",
        start_line: MARKER_LINE + 2,
        end_line: LEGACY_END + 2,
        reason: "legacy, scheduled for removal",
      },
    ]);
  });
});

describe("the text report", () => {
  it("names every bypassed region and the added lines they hid, before the findings", () => {
    const lines = branchReviewText("main", "HEAD", {
      findings: [],
      bypassed: 2,
      bypass_regions: [
        { path: "svc.ts", start_line: 7, end_line: 21, reason: "legacy" },
        { path: "whole.ts", start_line: 1, end_line: 4, reason: "generated" },
      ],
    });
    expect(lines).toEqual([
      "\n=== Branch review: HEAD vs main ===",
      "No issues found.",
      "Review was bypassed by markers in the code in 2 region(s): svc.ts:7-21 (legacy), whole.ts:1-4 (generated); read those yourself.",
      "2 added line(s) in bypassed regions were not reviewed.",
    ]);
  });

  it("names the markers the change added, which were not honoured", () => {
    const lines = branchReviewText("main", "HEAD", {
      findings: [],
      bypass_added: [{ path: "svc.ts", line: 3, reason: "trust me" }],
    });
    expect(lines).toContain(
      "This change adds 1 bypass marker(s): svc.ts:3 (trust me). They were not honoured -- the blocks were reviewed -- and take effect once merged; judge them now.",
    );
  });

  it("says nothing about bypassing when nothing was bypassed", () => {
    const lines = branchReviewText("main", "HEAD", {
      findings: [],
      bypassed: 0,
      bypass_regions: [],
    });
    expect(lines).toEqual(["\n=== Branch review: HEAD vs main ===", "No issues found."]);
  });
});
